addons:
    apt:
        packages:
            - python-pygments

install:
    - rm -rf public || exit 0

script:
    - cd src/
    - ./hugo --theme=academic

deploy:
    provider: script
    script: deploy.sh
    on:
        branch: deployment
