addons:
    apt:
        packages:
            - python-pygments

install:
    - rm -rf public || exit 0

before_script:
    - chmod +x ./deploy.sh
    - chmod +x src/hugo

script:
    - cd src/
    - ./hugo --theme=academic

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: public
    target_branch: master
    github_token: $GITHUB_TOKEN
    on:
        branch: deployment
