addons:
    apt:
        packages:
            - python-pygments

install:
    - rm -rf public || exit 0

before_script:
    - chmod +x ./deploy.sh
    - chmod +x src/hugo

script:
    - cd src/
    - ./hugo --theme=academic

before_deploy:
    - cd ../

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: deployment

after_deploy:
    - curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
    - git checkout gh-pages
    - chmod a+x /tmp/travis-automerge
    - BRANCHES_TO_MERGE_REGEX='^gh-pages$' BRANCH_TO_MERGE_INTO=master GITHUB_SECRET_TOKEN=$GITHUB_TOKEN GITHUB_REPO=SiddarthKrishnamoorthy/SiddarthKrishnamoorthy.github.io /tmp/travis-automerge"
