addons:
    apt:
        packages:
            - python-pygments

install:
    - rm -rf public || exit 0

script:
    - cd src/
    - ./hugo --theme=academic

deploy:
    provider: script
    skip_cleanup: true
    local_dir: public
    script: deploy.sh
    on:
        branch: deployment
