addons:
    apt:
        packages:
            - python-pygments

install:
    - rm -rf public || exit 0

before_script:
    - chmod +x ./deploy.sh
    - chmod +x src/hugo

script:
    - cd src/
    - ../deploy.sh

